### PR TITLE
Revised the admin CMS flow

### PR DESCRIPTION
**Pull request by hasandi**

### CODE REVIEW

**Comment by hasandi** [comment]
Menjawab:
1. Kalimat 'Please login' kayaknya nggak akan menjadi major problem. Let it be.
2. Solved by latest commit.
3. Solved by latest commit.
4. Solved by latest commit.
5. Untuk sementara sepertinya bisa diabaikan

**Comment by ifanasution** [comment]
Error found:
1. Approve transaction:
UnexpectedValueException in Response.php line 403:
The Response content must be a string or object implementing __toString(), "boolean" given.

2. Pagination sort: pas udah nge-sort terus pindah page, sort nya udah gak berlaku

**Comment by hasandi** [comment]
Mohon bantuannya @kevinega

**Comment by ifanasution** [comment]
capture
@kevinega ga error ini knp ya?

**Comment by kevinega** [comment]
@hasandi @ifanasution 
Issue 1. Solved by latest commit
Issue 2. Solved by latest commit

Silahkan di cek kembali thankyou :)

**Pull request merged**
