### PR TITLE
Cover Photo

### PR DESCRIPTION
**Pull request by nayawn**
jangan lupa composer install buat image intervention

### CODE REVIEW

**Comment by hasandi** [comment]
Gambar yang di-upload masih ke-stretch ya?

**Comment by ifanasution** [comment]
@hasandi screenshot dundd

**Comment by hasandi** [comment]
@ifanasution nih screenshot-nya capture

**Comment by ifanasution** [comment]
@hasandi hmm harusnya udh engga

**Comment by ifanasution** [comment]
@hasandi di gue sih udh bener harusnya begini:

**Comment by hasandi** [comment]
@ifanasution di laptop gua masih sama aja hehe

**Comment by hasandi** [comment]
Tambahan:
Di laptop gua kalau zoom level-nya 100% tetep nge-stretch, tapi kalau zoom level-nya dikurangin jadi 75% jadi bener. Which means gambarnya berarti ikut stretching bareng `<div>` yang bersangkutan. Monggo diselesaikan terlebih dahulu

**Comment by hasandi** [comment]
@ifanasution unfortunately, still the same
capture

**Comment by hasandi** [comment]
Everything solved. Nice job @ifanasution

**Pull request merged**
