### PR TITLE
[HOTFIX] Upload/Edit Cover

### PR DESCRIPTION
**Pull request by ifanasution**
New updates:
1. fixing button modal when zoom in
2. fixing choose file image to non-image
3. fixing display error append

### CODE REVIEW

**Comment by ifanasution** [comment]
@hasandi @kevinega @ramramtul ini juga tolong di coba ya gais

**Comment by kevinega** [comment]
@ifanasution @nayawn ini emang gaada batasan minimal pixel yg di crop ya?
handling crop sangat kecil

**Comment by nayawn** [comment]
Takadaa

**Comment by kevinega** [comment]
@ifanasution @nayawn file gif masih belom di handlle nih.
handle file gif

**Comment by ifanasution** [comment]
@kevinega emg kalo cover gaboleh gif, ya kan ya? @nayawn

**Comment by hasandi** [comment]
Please fix the error message @ifanasution @ramramtul @kevinega.
image

**Comment by hasandi** [comment]
There are no clock input when opened in Mozilla Firefox.
image

**Comment by ifanasution** [comment]
@hasandi kalo nanti di merge sama cover harusnya udah benerrrr

**Comment by hasandi** [comment]
@ifanasution ini kan cover..?

**Pull request merged**
